public static class KafkaProducerConfigEnvVars
{
    public const string KAFKA_BATCH_NUM_MESSAGES = nameof(KAFKA_BATCH_NUM_MESSAGES);
    public const string KAFKA_COMPRESSION_TYPE = nameof(KAFKA_COMPRESSION_TYPE);
    public const string KAFKA_QUEUE_BUFFERING_BACKPRESSURE_THRESHOLD = nameof(KAFKA_QUEUE_BUFFERING_BACKPRESSURE_THRESHOLD);
    public const string KAFKA_RETRY_BACKOFF_MS = nameof(KAFKA_RETRY_BACKOFF_MS);
    public const string KAFKA_MESSAGE_SEND_MAX_RETRIES = nameof(KAFKA_MESSAGE_SEND_MAX_RETRIES);
    public const string KAFKA_LINGER_MS = nameof(KAFKA_LINGER_MS);
    public const string KAFKA_QUEUE_BUFFERING_MAX_KBYTES = nameof(KAFKA_QUEUE_BUFFERING_MAX_KBYTES);
    public const string KAFKA_QUEUE_BUFFERING_MAX_MESSAGES = nameof(KAFKA_QUEUE_BUFFERING_MAX_MESSAGES);
    public const string KAFKA_ENABLE_GAPLESS_GUARANTEE = nameof(KAFKA_ENABLE_GAPLESS_GUARANTEE);
    public const string KAFKA_ENABLE_IDEMPOTENCE = nameof(KAFKA_ENABLE_IDEMPOTENCE);
    public const string KAFKA_TRANSACTION_TIMEOUT_MS = nameof(KAFKA_TRANSACTION_TIMEOUT_MS);
    public const string KAFKA_TRANSACTIONAL_ID = nameof(KAFKA_TRANSACTIONAL_ID);
    public const string KAFKA_COMPRESSION_LEVEL = nameof(KAFKA_COMPRESSION_LEVEL);
    public const string KAFKA_PARTITIONER = nameof(KAFKA_PARTITIONER);
    public const string KAFKA_MESSAGE_TIMEOUT_MS = nameof(KAFKA_MESSAGE_TIMEOUT_MS);
    public const string KAFKA_REQUEST_TIMEOUT_MS = nameof(KAFKA_REQUEST_TIMEOUT_MS);
    public const string KAFKA_DELIVERY_REPORT_FIELDS = nameof(KAFKA_DELIVERY_REPORT_FIELDS);
    public const string KAFKA_ENABLE_DELIVERY_REPORTS = nameof(KAFKA_ENABLE_DELIVERY_REPORTS);
    public const string KAFKA_ENABLE_BACKGROUND_POLL = nameof(KAFKA_ENABLE_BACKGROUND_POLL);
    public const string KAFKA_BATCH_SIZE = nameof(KAFKA_BATCH_SIZE);
    public const string KAFKA_STICKY_PARTITIONING_LINGER_MS = nameof(KAFKA_STICKY_PARTITIONING_LINGER_MS);
}
