networks:
  apps_network:
    name: apps_network
    external: true

services:
  key-value-api:
    image: localhost/key-value-api
    container_name: key-value-api
    build:
      context: ./Code/KeyValueApi
      dockerfile: Dockerfile
    user: 1000:1001
    networks:
      - apps_network
    ports:
      - "8080:8080"
    volumes:
      - ./ContainerData/GeneratedCerts/Kafka/Users/Admin:/kafka/secrets
      - ./ContainerData:/ContainerData
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_URLS: "http://+:8080"

      # KAFKA_BOOTSTRAP_SERVERS: "broker1:9092,broker2:9092,broker3:9092"
      # KAFKA_CLIENT_CERTIFICATE_PEM_LOCATION: "/kafka/secrets/admin.lokalmaskin.crt"
      # KAFKA_CLIENT_KEY_PASSWORD_LOCATION: "/kafka/secrets/admin.lokalmaskin.password.txt"
      # KAFKA_CLIENT_KEY_PEM_LOCATION: "/kafka/secrets/admin.lokalmaskin.key"
      # KAFKA_TRUST_STORE_PEM_LOCATION: "/kafka/secrets/CA_lokalmaskin.crt"

      # kafkal client config
      KAFKA_BOOTSTRAP_SERVERS: "broker1:9092,broker2:9092,broker3:9092"
      KAFKA_SECURITY_PROTOCOL: "ssl"
      KAFKA_SSL_CA_PEM_LOCATION: "/kafka/secrets/CA_lokalmaskin.crt"
      KAFKA_SSL_CERTIFICATE_LOCATION: "/kafka/secrets/admin.lokalmaskin.crt"
      KAFKA_SSL_KEY_LOCATION: "/kafka/secrets/admin.lokalmaskin.key"
      KAFKA_SSL_KEY_PASSWORD: "/kafka/secrets/admin.lokalmaskin.password.txt"
      KAFKA_ACKS: "all"

      # Consumer config
      KAFKA_GROUP_ID: "cg.experimental"
      KAFKA_ENABLE_AUTO_COMMIT: "true"
      KAFKA_AUTO_COMMIT_INTERVAL_MS: "200"
      KAFKA_AUTO_OFFSET_RESET: "Earliest"

      # Producer config
      KAFKA_LINGER_MS: "10"

      KAFKA_KEY_VALUE_TOPIC: "t.key-value-store"
      KAFKA_SCHEMA_REGISTRY_ADDRESS: "http://schema-registry:8083"
      KEY_VALUE_STORE_ROOT_DIR: "/ContainerData/KeyValueApi/LocalState"
      KV_API_AES_KEY: "513925caed8f4774d04d1013bef95cdb37d4f78a01965f25390da8ad9b6da15a"

      # KV_API_ENCRYPT_DATA_IN_STATE_STORAGE: "false"
      KV_API_ENCRYPT_DATA_IN_STATE_STORAGE: "true"

      # KV_API_ENCRYPT_DATA_ON_KAFKA: "false"
      KV_API_ENCRYPT_DATA_ON_KAFKA: "true"

      KV_API_STATE_STORAGE_TYPE: "disk"
